### ISSUE TITLE
[PE-D][Tester C] Inconsistency of note command format throughout the UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F15-3/tp#134]
![image.png](https://raw.githubusercontent.com/KSSWSept20/ped/main/files/36febd78-2e10-4f71-bd00-239722f384fd.png)

![image.png](https://raw.githubusercontent.com/KSSWSept20/ped/main/files/1b459af6-9d4d-4a12-9e37-3aca39163b56.png)

I think it is better to make the command format of export to be consistent as now in UG, the command summary is saying to type "/export", while the table of content and the export command section under features and the examples given underneath are using "export" without the "/".

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: KSSWSept20/ped#3

**Comment by lihaoquan** [comment]
Duplicate
