### ISSUE TITLE
[PE-D][Tester B] Misleading error message with edit command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F15-3/tp#137]
## Steps to Reproduce

Run the command: `edit 1 /stage STAGE`

where `STAGE` is the stage where the 1st contact on the filtered person list is at.

## Expected

An error message such as
```
The contact <contact name> is already at stage <stage>
```

## Actual

![image.png](https://raw.githubusercontent.com/JuliaPoo/ped/main/files/a53ea22e-cefb-4481-9c81-8092cd2db331.png)

```
This applicant already exists in the address book.
```

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: JuliaPoo/ped#2

**Comment by ChrisHo1341** [comment]
Probably need to have a few different error messages for this
