### ISSUE TITLE
[PE-D][Tester D] Title of the email template not matching

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F15-3/tp#151]
![image.png](https://raw.githubusercontent.com/Ty-stan0417/ped/main/files/0a1457ca-11c3-4dae-aecd-369428fcefb5.png)

The title of the new window when click Email button should not be Help

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Ty-stan0417/ped#8

**Comment by ChrisHo1341** [comment]
Is this a Ui bug? Allowed to fix?

I think it is not purely cosmetic
