### ISSUE TITLE
[PE-D][Tester E] UG filename is still AB-3

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F15-3/tp#166]
**1.steps to reproduce:**
Read the UG command summary.

**2.expected:**
UG filename to be changed into HRConnect.

**3.actual:**
It's still AB-3

**4.screenshots**

![image.png](https://raw.githubusercontent.com/nusliuyifan/ped/main/files/629d5ccc-a044-4b37-93be-0639a35ced29.png)

**5.good way to improve the product:**
Change it to your project name.

-------------
Labels: `severity.High` `type.DocumentationBug`
original: nusliuyifan/ped#7

**Comment by ys112** [comment]
- [ ] Modified scss
