### ISSUE TITLE
[PE-D][Tester D] Add command cannot add stage

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F15-3/tp#167]
Suppose the add command can add stage by logic, by I only can use edit to add the stage to the specific person.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Ty-stan0417/ped#14

**Comment by xinen26** [comment]
Out of scope for now.

**Comment by ys112** [comment]
Can be a UG issue.

**Comment by ys112** [comment]
- [ ] Stated explicitly in UG
- [ ] Add flow diagram to enhance sequence in DG?
