### ISSUE TITLE
UG Update - Future Enhancements

### ISSUE THREAD

**Issue by lihaoquan** [AY2324S2-CS2103-F15-3/tp#200]
#129 
#169
#142
#152
~#154~ (see below)
#168
#174
#177
#184
#190
#131
#175

**Comment by ys112** [comment]
#188

**Comment by ys112** [comment]
#195

**Comment by ChrisHo1341** [comment]
#133

**Comment by ys112** [comment]
For tester D,

#185

**Comment by ys112** [comment]
Can be resolved with User guide specifications:
#154

**Comment by ys112** [comment]
Completed.
