### ISSUE TITLE
NoteCommandTest failing

### ISSUE THREAD

**Issue by ys112** [AY2324S2-CS2103-F15-3/tp#48]
Issue: execute_addNoteUnfilteredListWithDate_success() seems to have different fields supplied causing the test to fail.

Expected:
`seedu.address.logic.commands.CommandResult{feedbackToUser=Added note to Person: seedu.address.model.person.Person{name=Alice Pauline, phone=94351253, email=alice@example.com, address=123, Jurong West Ave 6, #08-111, tags=[[friends]], note=Updated Note, noteDate=}, showHelp=false, exit=false}`

Actual:
`seedu.address.logic.commands.CommandResult{feedbackToUser=Added note to Person: seedu.address.model.person.Person{name=Alice Pauline, phone=94351253, email=alice@example.com, address=123, Jurong West Ave 6, #08-111, tags=[[friends]], note=Updated Note, noteDate=March 15, 24}, showHelp=false, exit=false}`

@lihaoquan, please note the following issue thanks.

**Comment by lihaoquan** [comment]
Resolved by #53
