### ISSUE TITLE
Update the Developer Guide 

### ISSUE THREAD

**Issue by YuvBindal** [AY2324S2-CS2103-F15-3/tp#5]
As a developer, I can view the user guide to see how myself and my colleagues have contributed to the project.

**Comment by YuvBindal** [comment]
Responsibilities:
- Target user profile, value proposition, and user stories: @ys112 and @ChrisHo1341 
- Use cases: @xinen26 
- NFRs: @YuvBindal 
- Glossory: @ChrisHo1341 and @ys112

**Comment by ys112** [comment]
Add target user profile, value proposition, and user stories into developer guide #11
