### ISSUE TITLE
As a user I can read the user guide,

### ISSUE THREAD

**Issue by ys112** [AY2324S2-CS2103-F15-3/tp#6]
so that I can know how to use HRConnect.

**Comment by ys112** [comment]
Responsibilities:

- [ ] In General: @lihaoquan 
- [ ] Filter: @ys112 
- [ ] Tag: @ChrisHo1341 
- [ ] Notes: @xinen26 
- [ ] Export contacts: @YuvBindal

**Comment by ys112** [comment]
Filter done #10

**Comment by ys112** [comment]
add filter in UG #10

**Comment by lihaoquan** [comment]
#22 #23
